language: android
before_install:
- nvm install 6
- node --version
install:
- npm install
- npm install -g ionic cordova 
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
script:
- ionic cordova build android --release
deploy:
  skip_cleanup: true
  provider: releases
  file: $TRAVIS_BUILD_DIR/platforms/android/build/outputs/apk/android-release-unsigned.apk
  on:
    repo: LeonardoGastonRossi/IonicTest
    tags: true
